import Sidebar from "@/components/layout/sidebar";
import type { Metadata } from "next";
import { Red_Hat_Text } from "next/font/google";
import "./globals.css";

export const poiret = Red_Hat_Text({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Imagine Dragons",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poiret.className} antialiased grid grid-cols-[250px_1fr] bg-[#f4f4f4]`}
      >
        <Sidebar />
        <main className="">{children}</main>
      </body>
    </html>
  );
}
